### ISSUE TITLE
Doesnt extract projectfile?

### ISSUE THREAD

**Issue by Garzhad** [Petschko/RPG-Maker-MV-Decrypter#13]
Im not sure if its supposed to or not, but unlike the other versions of the rpgmaker decryptor programs, this one doesnt extract the .rpgmaker project file with which you need to open it in rpgmakerMV program?

**Comment by Petschko** [comment]
There was a workaround for this. You can just create the Project-File by yourself since the Content of the Project-File is not relevant. Create a new Project with the RPG-Maker MV and open your Project-File in a Text-Editor you just have this content:
File-Name: Game.rpgproject
```txt
RPGMV 1.3.1
```

MAKE A BACKUP before doing that step:
I think you have to create this File (With the Content above) in the Root-Dir of your Game `{GameDir}/Game.rpgproject` and re-build the File-Structure:
In the most Games you have to copy ALL Content from `{GameDir}/www/*` to `{YourGameDir}/*` _(Into the root where the Game.rpgproject file is)_.
After that you should be able to open the Game (IDK if it needs encrypted or decrypted Files so serve both, just in case)

Give it a try^^

**Comment by Garzhad** [comment]
Okay yeah that let me open the game up. Looking at maps most tiles are blank though. Perhaps need dlcs to see the terrain properly, i dunno.

**Comment by Petschko** [comment]
Did you provide all Images as encrypted AND decrypted versions? (In {GameDir}/img/* and in {GameDir}/www/img/*)
Try it if you not already have done this

**Comment by Petschko** [comment]
Did you solve your problem?^^
