### ISSUE TITLE
Chrome tab crashes ZIPing 2k files

### ISSUE THREAD

**Issue by falcon4fun** [Petschko/RPG-Maker-MV-Decrypter#16]
Vodka, Putin, Balalayka. Hallo.

I tryed v1.0 on 900-1000 (of 1900+) files (1.1+ GB). Chrome tab crashed (64.0.3269.3 dev).
But 800-850 files works fine.
FF works fine making archive of all 1900 files

Can smb test this case? Dev? (:

**Comment by Petschko** [comment]
The Browsers have a Maximum amount of Memory, which can stored into the Browser. Do you know MEGA? It uses the same Technique, if there is a file, which is bigger than ~1GB it tolds you to install an extension. That's the same reason, because Browsers can't handle to much into the momory.

May the Firefox has a bit more memory nowadays, since they improved the memory handling of it in Version 57. But the Firefox will also have a limit.

Does this answer your question?^^

**Comment by falcon4fun** [comment]
Yeap :) Thank you.
More interesting that browser can't allocate more memory on 64-bit version (so no 3.5 GB limitation) when having 32+GB RAM installed.. :D

**Comment by Petschko** [comment]
I'm unsure why there is a limit. Normaly they should be able to allocate more memory but may this is internal limited per tab.
To be honest why should a website need to use so much memory in normal cases^^
