### ISSUE TITLE
It cannot use to decrypt a game file 

### ISSUE THREAD

**Issue by Flagred** [Petschko/RPG-Maker-MV-Decrypter#19]
I cannot decrypt stranger of power 2 resources , help with the file if you can or help me to decrypt it if you can. I no sure if i done something wrong or wha. Do help to check it thank.
![screenshot_20180529081356](https://user-images.githubusercontent.com/39714944/40632331-51bb1fdc-6318-11e8-85ce-0d1503ce2f64.png)

**Comment by Petschko** [comment]
Please note, that I already work on a method to automate this, see here:
https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/18

**Comment by Flagred** [comment]
Oh ok it do work, thank you so much for the help. I really appreciate your effort there. A first time i thought the data file of rpg game that been compress cannot be decrypt... thank you very much for your hard work. 
Anyway can i have your mail ? I promise i wont spam you. I no sure if i can find your mail here but do correct me if you already put your mail somewhere in here. Thank again for your help.

**Comment by Petschko** [comment]
Hey, my Mail is peter@petschko.org

usually its on my Github profile and on the Decrypt-Tool in the bottom (also within my imprint).

Please upload that game at mega or so and send me the link via mail then^^

**Comment by Flagred** [comment]
I hope you check your mail as the link been send some day ago. Anyway, can you share fantasy heroine pack 1 and 2 if you got?

**Comment by Petschko** [comment]
Yes I received it, sadly its not a link what you send me there, please send me a link with a download or such stuff

Before you send the link to me, please try out if it works and start with **http://** or **https://** I don't install any Extensions to download stuff^^
If your link has **chrome-extension://** as start, it's not a valid link

**Comment by Flagred** [comment]
Just copy paste it to any browser... It should work... Anyway that link is no by me... If no work then I will take time upload myself as my country internet speed is slow...

**Comment by Petschko** [comment]
I think you can just upload some files of it, like the system.json, the rpg_core.js and a sample encrypted image.

I don't want to play the game, I just need these 3 Files (System.json, rpg_core.js and a encrypted file) and about your link, no it doesn't work
chrome-extension://**bigefpfhnfcobdlfbedofhhaibnlghod**/mega/secure.html(...)
doesn't even has a target server (Bold) nor the protocol "chrome-extension" exists. It just opens my search engine with the request to search for this, which makes sense since its not a URL
