### ISSUE TITLE
Game has changed their .json to custom file extension instead? Can I still find encryption key?

### ISSUE THREAD

**Issue by imbadatcreatingnames** [Petschko/RPG-Maker-MV-Decrypter#28]
I was planning to re-encrypt some files because I was making a custom sprite mod for a game called OMORI, but the .JSON file (which is in www/data) has been set to a custom file extension (named after one of the characters) .KEL. I've had a search around and I don't think I've found any mention of a way to do this on RPG maker forums so this might be an individual thing, but I thought if anybody knew about encryption of RPG maker files it'd be the guy who made this. I tried just putting it in, but it just comes out with an "it's not a JSON" message. 
Do you know any way to get this in a working .JSON format? I tried literally just changing the file extension but it comes out unreadable (unsurprisingly). Is this impossible to get working? Or am I being a moron and there's actually a super obvious fix to this?

**Comment by Petschko** [comment]
It would help if you send the file, else i can just guess^^

**Comment by imbadatcreatingnames** [comment]
Oh shoot didn't expect such a quick response. Here's the file! 
https://drive.google.com/file/d/1W4sHnQoSu_RNS3l_2_Mg2KcFnf-uMUUQ/view?usp=sharing

**Comment by Petschko** [comment]
Thats indeed no JSON-File, they probably used an other tool to encrypt the Game. Maybe they used the default RPG-Maker encryption method on top of that, but this looks like a custom encryption (no wide used tool)

I think its a custom encryption method by the Developer, since even that File-Extension doesnt exists (Never saw it nor Internet search gives results)

In the end every game can be decrypted if enough power of finding out is put into it, since the RPG-Maker games work locally and even AAA-Companies can't encrypt their Resources from people.
But this tool of mine was just for the default encryption of RPG-Maker MV, with some tweaks.

If its a Fan-Mod, why don't you ask the owner of the Game? You can at least try, else you have to find out yourself or take a look at F95-Zone, maybe someone there can help you =) Either the encryption method is somewhere visible in the game or you can find out the key/file via memory dump when running the game

Well my Tool could help you to at least get the images without any key, but for a mod you need access to different stuff i think.

**Comment by AyoImhere** [comment]
Watch This https://www.youtube.com/watch?v=-KBIrByGi5M&ab_channel=TinyTimGames

**Comment by lunaisnotaboy** [comment]
I doubt anybody is still interested in this, but OMORI added this snippet to the end of `rpg_managers.js`:

```javascript
(function() {
  const crypto = require("crypto")
  const path = require("path");
  const fs = require("fs");
  
  const algorithm = "aes-256-ctr";
  let steamkey = String(window.nw.App.argv).replace("--", "");
  
  const applySteamLibrary = (plugins) => {
      const i = plugins.slice(0,16);
      plugins = plugins.slice(16);
      const d = crypto.createDecipheriv(algorithm, steamkey, i);
      const r = Buffer.concat([d.update(plugins), d.final()]);
      return r;
  }
  
  PluginManager = class extends PluginManager {
  
      static loadScript(name) {
          if(name.contains("vorbis")) {return super.loadScript(name)}
          name = name.replace(".js", ".OMORI").replace(".JS", ".OMORI");
          var base = path.dirname(process.mainModule.filename);
          let buff = fs.readFileSync(base + "/" + this._path + name);
          var url = this._path + name;
          var script = document.createElement('script');
          script.type = 'text/javascript';
          script.innerHTML = applySteamLibrary(buff).toString()
          script._url = url;
          document.body.appendChild(script);
  
      }
  }
})()
```

That should help with the `.OMORI` files.

**Comment by hehekal328** [comment]
I’m having the same problem. I’m trying to get the audio from OMORI but I need the encryption key.
