### ISSUE TITLE
Can't find Decryption code.

### ISSUE THREAD

**Issue by Tungstenium210** [Petschko/RPG-Maker-MV-Decrypter#42]
Hello there. There is problem with this game. https://nemlei.itch.io/the-coffin-of-andy-and-leyley
I tried using your site, to decrypt PNG, but they are not open properly.
I tried to find Decryption code manually  in system.json (find d41d8cd98f00b204e9800998ecf8427e but seems code is "fake") and in rpg_core.js (find Decrypter.readEncryptionkey = function(){  this._encryptionKey = $dataSystem.encryptionKey.split(/(.{2})/).filter(Boolean);) 
Gonna send also system.json and rpg_core.js

[files.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/11524414/files.zip)

I hope you can help me)

**Comment by Petschko** [comment]
Try to use the "Restore Images"-Option, if that didnt work, the game probably uses a different encryption method. You can also select an encrypted PNG file for getting the key.
This tool is for the default encryption of RPG-Maker MV/MZ, so yeah if these options dont work the Game-Dev uses a custom method for that

**Comment by Petschko** [comment]
Also see https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/42

**Comment by Petschko** [comment]
Also as additional information for you:

1. RPG-Maker MV & MZ encrypt only the **first 16 bytes** of a file.
2. The "Restore Image" function replaces the **first 16 bytes** of the encrypted PNG with the default first 16 bytes of an PNG, since they **are always the same**.

Since the image was still not viewable, it seems there is an other encryption method, else this had worked

This Game has some custom encryption in it and further Issues about this game will be closed and linked to this issue
